In [2]:
import numpy as np

In [3]:
my_list1 = [1,2,3,4]

In [4]:
my_array1 = np.array(my_list1)

In [5]:
my_array1

array([1, 2, 3, 4])

In [6]:
my_list2 = [11,22,33,44]

In [7]:
my_lists = [my_list1,my_list2]

In [8]:
my_lists

[[1, 2, 3, 4], [11, 22, 33, 44]]

In [9]:
my_array2 = np.array(my_lists)

In [10]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [11]:
my_array2.shape

(2, 4)

In [12]:
my_array2.dtype

dtype('int64')

In [13]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [14]:
my_zeros = np.zeros(5)

In [15]:
my_zeros.dtype

dtype('float64')

In [16]:
np.ones((5.5))

TypeError: 'float' object cannot be interpreted as an integer

In [17]:
np.ones((5,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [18]:
np.empty

<function numpy.core.multiarray.empty>

In [19]:
np.empty((3,4))

array([[ -3.10503618e+231,  -3.11109526e+231,   2.96439388e-323,
          0.00000000e+000],
       [  2.12199579e-314,   4.47032019e-038,   5.94604830e-091,
          1.39380322e+165],
       [  8.40871251e+164,   3.22115228e-057,   3.99910963e+252,
          8.34402701e-309]])

In [20]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [21]:
np.arrange(5
)

AttributeError: module 'numpy' has no attribute 'arrange'

In [22]:
np.arrange(5)

AttributeError: module 'numpy' has no attribute 'arrange'

In [23]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [24]:
np.arange(5,50,3)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])